GOOS=android GOARCH=arm go build -o -v release/android-arm/thtml .
GOOS=darwin GOARCH=386 go build -o -v release/darwin-386/thtml .
GOOS=darwin GOARCH=amd64 go build -o -v release/darwin-amd64/thtml .
GOOS=darwin GOARCH=arm go build -o -v release/darwin-arm/thtml .
GOOS=darwin GOARCH=arm64 go build -o -v release/darwin-arm64/thtml .
GOOS=dragonfly GOARCH=amd64 go build -o -v release/dragonfly-amd64/thtml .
GOOS=freebsd GOARCH=386 go build -o -v release/freebsd-386/thtml .
GOOS=freebsd GOARCH=amd64 go build -o -v release/freebsd-amd64/thtml .
GOOS=freebsd GOARCH=arm go build -o -v release/freebsd-arm/thtml .
GOOS=linux GOARCH=386 go build -o -v release/linux-386/thtml .
GOOS=linux GOARCH=amd64 go build -o -v release/linux-amd64/thtml .
GOOS=linux GOARCH=arm go build -o -v release/linux-arm/thtml .
GOOS=linux GOARCH=arm64 go build -o -v release/linux-arm64/thtml .
GOOS=linux GOARCH=ppc64 go build -o -v release/linux-ppc64/thtml .
GOOS=linux GOARCH=ppc64le go build -o -v release/linux-ppc64le/thtml .
GOOS=linux GOARCH=mips go build -o -v release/linux-mips/thtml .
GOOS=linux GOARCH=mipsle go build -o -v release/linux-mipsle/thtml .
GOOS=linux GOARCH=mips64 go build -o -v release/linux-mips64/thtml .
GOOS=linux GOARCH=mips64le go build -o -v release/linux-mips64le/thtml .
GOOS=linux GOARCH=s390x go build -o -v release/linux-s390x/thtml .
GOOS=netbsd GOARCH=386 go build -o -v release/netbsd-386/thtml .
GOOS=netbsd GOARCH=amd64 go build -o -v release/netbsd-amd64/thtml .
GOOS=netbsd GOARCH=arm go build -o -v release/netbsd-arm/thtml .
GOOS=openbsd GOARCH=386 go build -o -v release/openbsd-386/thtml .
GOOS=openbsd GOARCH=amd64 go build -o -v release/openbsd-amd64/thtml .
GOOS=openbsd GOARCH=arm go build -o -v release/openbsd-arm/thtml .
GOOS=plan9 GOARCH=386 go build -o -v release/plan9-386/thtml .
GOOS=plan9 GOARCH=amd64 go build -o -v release/plan9-amd64/thtml .
GOOS=solaris GOARCH=amd64 go build -o -v release/solaris-amd64/thtml .
GOOS=windows GOARCH=386 go build -o -v release/windows-386/thtml .
GOOS=windows GOARCH=amd64 go build -o -v release/windows-amd64/thtml .

for i in release/*; do zip -r "$i".zip "$i"; done